# Generated by Django 3.1.7 on 2021-03-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0003_auto_20210328_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instytucja', 'verbose_name_plural': 'Instytucje'},
        ),
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
